version: "3.3"

services:
  snikket_proxy:
    container_name: snikket-proxy
#    image: snikket/snikket-web-proxy:dev
    build:
     context: ./snikket-web-proxy
     dockerfile: Dockerfile
    env_file: snikket.conf
    network_mode: host
    volumes:
      - snikket_data:/snikket
      - acme_challenges:/var/www/html/.well-known/acme-challenge
    restart: "unless-stopped"
  snikket_certs:
    container_name: snikket-certs
#    image: snikket/snikket-cert-manager:dev
    build:
     context: ./snikket-certs
     dockerfile: Dockerfile
    network_mode: host
    env_file: snikket.conf
    volumes:
      - snikket_data:/snikket
      - acme_challenges:/var/www/.well-known/acme-challenge
    restart: "unless-stopped"
  snikket_portal:
    container_name: snikket-portal
#    image: snikket/snikket-web-portal:dev
    build:
     context: ./snikket-web-portal
     dockerfile: Dockerfile
    network_mode: host
    env_file: snikket.conf
    restart: "unless-stopped"

  snikket_server:
    container_name: snikket
#    image: snikket/snikket-server:dev
    build:
     context: ./snikket-server
     dockerfile: Dockerfile
    network_mode: host
    volumes:
      - snikket_data:/snikket
    env_file: snikket.conf
    restart: "unless-stopped"

volumes:
  acme_challenges:
  snikket_data:
