---

- name: "Add helper scripts"
  copy:
    src: "../files/bin/"
    dest: "/usr/local/bin/"
    mode: 0755

- name: "Install qrencode"
  apt:
    name: qrencode
    state: present

- name: 
  ansible.builtin.shell: prosodyctl install --server=https://modules.prosody.im/rocks/ mod_auth_ldap
  
