---
# Main playbook

- hosts: all
  become: yes
  gather_facts: no
  vars:
    prosody:
      package: "prosody-trunk"
      build: "1544"
    prosody_modules:
      revision: "eb63890ae8fc"
  tasks:
    - import_tasks: tasks/prosody.yml
    - import_tasks: tasks/supervisor.yml
    - import_tasks: tasks/cron.yml
    - import_tasks: tasks/certs.yml
    - import_tasks: tasks/mail.yml
    - import_tasks: tasks/coturn.yml
    - import_tasks: tasks/scripts.yml
