---
# Main playbook

- hosts: all
  become: yes
  gather_facts: no
  vars:
    prosody:
      package: "prosody-trunk"
      snapshot: "2024-04-26"
    prosody_modules:
      revision: "512f912fdfa5"
  tasks:
    - import_tasks: tasks/prosody.yml
    - import_tasks: tasks/services.yml
    - import_tasks: tasks/cron.yml
    - import_tasks: tasks/certs.yml
    - import_tasks: tasks/mail.yml
    - import_tasks: tasks/coturn.yml
    - import_tasks: tasks/scripts.yml
